server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: dongjae123
spring:
  dagak:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dagak
      username: root
      password: ssafy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dagak
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    host: 3.143.74.33
    port: 6379
mybatis:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
openvidu:
  secret: MY_SECRET
  url: https://capstone-6.shop:4443/
