spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimssafy1030@gmail.com
    password: vzxkizmiaqcjrknm
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  dagak:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/dagak
      username: root
      password: ssafy
  security:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/security
      username: root
      password: ssafy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/dagak?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    h2:
      console:
        enabled: true
  redis:
    host: 43.202.55.218
    port: 6379
  mybatis:
    mapper-locations: classpath:mybatis/mappers/**/*.xml
openvidu:
  secret: MY_SECRET
  url: https://i10a404.p.ssafy.io/
server:
  servlet:
    context-path: /dagak
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: dongjae123

google:
  auth:
    url: https://oauth2.googleapis.com
    scope: email
  login:
    url: https://accounts.google.com
  redirect.uri: https://localhost:8080/dagak/user/googleOauth
  client:
    id: ENC(tp1c63jVBYQIRFiP2bwwUGIONiskvDMHTGdo+ljhAPdCdmSxbQG0ObNU3oVoi83J0+BSRB6WPpT8JIW4AHL6WcNG0T0aQm5oDRajvJwVGrhsD+LXNXsW0A==)
  secret: ENC(mOXhqgPNISKfS9rHypLRVJI/iBKZVWzTJn9wFHfAS0N8tfSGiFo6cGzh685eKCQa)


kakao:
  rest-api-key: ENC(elg++M1l38fYXRyoDJ28XlhK8SjI5ZABIBQvQzOCotYb5KYFk/ReukpOEh3mNgY/)
